# Numpy dummy part 2

A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4]) 
a

array([1, 2, 3, 4])

In [5]:
a.shape # size elements

(4,)

In [6]:
a.dtype

dtype('int32')

The type of the array can also be explicitly specified at creation time:



In [10]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [12]:
from numpy import pi

In [13]:
np.linspace(0,2,9) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
x = np.linspace(0,2*pi,100)
f = np.sin(x)
print(f)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

## Dots

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

In [16]:
c = np.array( [[[  0,  1,  2],
                [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])
print(c)
print(c.shape)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
(2, 2, 3)


In [20]:
c[1,...] # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [21]:
 c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

### Iterating 

In [24]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [34]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [36]:
for  row in b.flat:
    print(row)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Stacking together different arrays


In [37]:
a = np.floor(10*np.random.random((2,2)))
a

array([[8., 1.],
       [1., 0.]])

In [38]:
b = np.floor(10*np.random.random((2,2)))
b

array([[7., 7.],
       [8., 1.]])

In [39]:
np.vstack((a,b))

array([[8., 1.],
       [1., 0.],
       [7., 7.],
       [8., 1.]])

In [40]:
np.hstack((a,b))

array([[8., 1., 7., 7.],
       [1., 0., 8., 1.]])

## Copies and Views


In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b is a

True

In [10]:
b.shape

(10,)

In [46]:
a.shape

(10,)

In [11]:

id(b)

1981697190768

In [12]:
id(a)

1981697190768

Different array objects can share the same data. The view method creates a new array object that looks at the same data.



In [13]:
c = a.view()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
c is a

False

In [16]:
id(c)

1981697283376

### Deep Copy

The copy method makes a complete copy of the array and its data.


In [17]:
d = a.copy()

In [18]:
d is a

False

In [19]:
d.base is a

False

In [24]:
d[0] = 1
d

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Indexing with Boolean Arrays


In [28]:
a = np.arange(12).reshape(3,4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [30]:
import matplotlib.pyplot as plt

In [ ]:
def mandelbrot( h,w, maxit=20 ):
    """ Return image """
    y,x = np.ogrid[ -1.4:1.4:h*1j, -2:0.8:w*1j ]
    c = x+y*1j
    z = c
    divtime = maxit + np.zeros(z.shape, dtype=int)

    for i in range(maxit):
        z = z**2 + c
        diverge = z*np.conj(z) > 2**2            # who is diverging
        div_now = diverge & (divtime==maxit)  # who is diverging now
        divtime[div_now] = i                  # note when
        z[diverge] = 2                        # avoid diverging too much
    return divtime