# NumPy basics

In [4]:
data =  list(range(5))
print(data)

[0, 1, 2, 3, 4]
[0.0, 2.5, 5.0, 7.5, 10.0]


although this technique is inefficient and slow, especially when we want to evaluate functions, polynomials or any other mathematical operation that appears in any scientific problem.

An array can be created explicitly or from a list in the following way:




In [22]:
import numpy as np

In [35]:
%timeit  for i in range(1000000): pass
#%timeit for x in xrange(1000000): pass
%timeit for i in np.arange(1000000): pass

41.9 ms ± 6.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
102 ms ± 14.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [44]:
np.arange(10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
np.linspace(0,30,8)  # Array de 8 números, de 0 a 30 ambos incluidos

array([ 0.        ,  4.28571429,  8.57142857, 12.85714286, 17.14285714,
       21.42857143, 25.71428571, 30.        ])

indexing arrays

In [64]:
number = np.linspace(0,30,8)
print(number)
number[3:8]

number[-7] # return the value indexing  that  array

print(number[:]) 
print(number[2:8:2]) # Elements from the second to the seventh, but jumping two by two



[ 0.          4.28571429  8.57142857 12.85714286 17.14285714 21.42857143
 25.71428571 30.        ]
[ 0.          4.28571429  8.57142857 12.85714286 17.14285714 21.42857143
 25.71428571 30.        ]
[ 8.57142857 17.14285714 25.71428571]


In [65]:
len(number)

8

Correct form to know the size array (numpy)

In [66]:
number.shape

(8,)

In [75]:
all = np.arange(6)
all
data_float = all.astype('float')
print(type(data_float))
print(data_float.shape)

<class 'numpy.ndarray'>
(6,)


In [81]:
x = np.array([5.6, 7.3, 7.7, 2.3, 4.2, 9.2])
print(x+data_float)
print(x*data_float)
print(x-data_float)

[ 5.6  8.3  9.7  5.3  8.2 14.2]
[ 0.   7.3 15.4  6.9 16.8 46. ]
[ 5.6  6.3  5.7 -0.7  0.2  4.2]


Concat new  elements to array

In [85]:
elements = np.concatenate((x,data_float))
print(elements)

[5.6 7.3 7.7 2.3 4.2 9.2 0.  1.  2.  3.  4.  5. ]


append elements to array

In [89]:
np.append(x,199)

array([  5.6,   7.3,   7.7,   2.3,   4.2,   9.2, 199. ])

insert  elements to array

In [91]:
np.insert(x,2,100)

array([  5.6,   7.3, 100. ,   7.7,   2.3,   4.2,   9.2])

In [96]:
np.insert(x, [2, 4,-1], [-10, -30,100])

[5.6 7.3 7.7 2.3 4.2 9.2]


array([  5.6,   7.3, -10. ,   7.7,   2.3, -30. ,   4.2, 100. ,   9.2])

## Arithmetic operations

In [108]:
print(x.max())
print(x.min())
print(x.mean()) # medium array value
print(x.std())
print(x.sum()) # sum all elements
print(np.median(x))

9.2
2.3
6.05
2.305609102457165
36.3
6.449999999999999


In [113]:
A = np.array([True,False,True])
B = np.array([False,True,False])
print(A * B)
C = np.array([1,2,3])
print(A * C)
print(B * C)

[False False False]
[1 0 3]
[0 2 0]



It is also very simple and more practical to create matrices using logical operators and then use them as indexes, for example:

In [116]:
my_array = np.arange(0, 100, 10)
i = np.arange(0, 10, 2)
indi2 = np.array([False, True, True, False, False, True, False, False, True, True])
print(my_array)
print(my_array[i])
print(my_array[indi2])

[ 0 10 20 30 40 50 60 70 80 90]
[ 0 20 40 60 80]
[10 20 50 80 90]


In [120]:
age50 = my_array > 50

print(age50)
print(my_array[age50])

[False False False False False False  True  True  True  True]
[60 70 80 90]


## Multidimensional matrix


In [122]:
arr0 = np.array([[10,20,30],[9, 99, 999],[0, 2, 3]])
print(arr0)

[[ 10  20  30]
 [  9  99 999]
 [  0   2   3]]


In [140]:
arr1 = np.zeros((2,3))
print(arr1)
print(arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [139]:
arr2 = np.ones((4,1))
print(arr2)
print(arr2.shape)

[[1.]
 [1.]
 [1.]
 [1.]]
(4, 1)


In [137]:
arr3 = np.arange(9).reshape((3, 3))
print(arr3)
print(arr3.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


access to elements multidimensional matrix

In [143]:
arr3[0,0]

0

In [146]:
# Primera columna
arr3[:,0]

array([0, 3, 6])

In [149]:
arr3[0,:] 
# Primera fila

array([0, 1, 2])

In [150]:
arr3[0,:2]
# primera fila

array([0, 1])

Update elements array

In [153]:
arr1[0,0] = 1
arr1

array([[1., 0., 0.],
       [0., 0., 0.]])

In [157]:
arr1[0,:] = [3,4,1]
arr1[0,:]

array([3., 4., 1.])

#  Changing the size of arrays

In [169]:
num = np.arange(10000) 
print(num)
print(num.shape)

[   0    1    2 ... 9997 9998 9999]
(10000,)


In [168]:
op2 = num.reshape((100,100))
print(op2)
print(op2.shape)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
(100, 100)


In [167]:
op3 = num.reshape((100,10,10))
print(op3)
print(op3.shape)

[[[   0    1    2 ...    7    8    9]
  [  10   11   12 ...   17   18   19]
  [  20   21   22 ...   27   28   29]
  ...
  [  70   71   72 ...   77   78   79]
  [  80   81   82 ...   87   88   89]
  [  90   91   92 ...   97   98   99]]

 [[ 100  101  102 ...  107  108  109]
  [ 110  111  112 ...  117  118  119]
  [ 120  121  122 ...  127  128  129]
  ...
  [ 170  171  172 ...  177  178  179]
  [ 180  181  182 ...  187  188  189]
  [ 190  191  192 ...  197  198  199]]

 [[ 200  201  202 ...  207  208  209]
  [ 210  211  212 ...  217  218  219]
  [ 220  221  222 ...  227  228  229]
  ...
  [ 270  271  272 ...  277  278  279]
  [ 280  281  282 ...  287  288  289]
  [ 290  291  292 ...  297  298  299]]

 ...

 [[9700 9701 9702 ... 9707 9708 9709]
  [9710 9711 9712 ... 9717 9718 9719]
  [9720 9721 9722 ... 9727 9728 9729]
  ...
  [9770 9771 9772 ... 9777 9778 9779]
  [9780 9781 9782 ... 9787 9788 9789]
  [9790 9791 9792 ... 9797 9798 9799]]

 [[9800 9801 9802 ... 9807 9808 9809]
  [9810 9811

## Masked Arrays

In [183]:
data = np.array([3, 7, -2, 6, 7, -8, 11, -1, -2, 8])
print(data)
mask = datos > 0
print(mask)
print(datos * mask)
print(datos[mask]) # show masked


[ 3  7 -2  6  7 -8 11 -1 -2  8]
[ True  True False  True  True False  True False False  True]
[ 3  7  0  6  7  0 11  0  0  8]
[ 3  7  6  7 11  8]


In [184]:
from numpy import  random

In [188]:
 values = random.randint(-10, 20, (10,2))
print(values)

[[-2 -1]
 [-7 12]
 [ 4 -1]
 [ 5 12]
 [ 0 -1]
 [15  8]
 [-6 19]
 [ 4 -9]
 [-5 17]
 [10 11]]


In [193]:
condition1 = values[:,0] > 0
condition1

array([False, False,  True,  True, False,  True, False,  True, False,
        True])

In [192]:
condition2 = values[:,1] < 10
condition2

array([ True, False,  True, False,  True,  True, False,  True, False,
       False])

In [195]:
mask_col0 = condition1*condition2
mask_col0

array([False, False,  True, False, False,  True, False,  True, False,
       False])

In [196]:
values[mask_col0]

array([[ 4, -1],
       [15,  8],
       [ 4, -9]])

## numpy.ma

In [199]:
import numpy.ma as ma

In [206]:
x = np.array([1, 2, 3, -1, 5])
mx = ma.masked_array(x, mask=[0, 0, 0, 1, 0])
print(mx)

[1 2 3 -- 5]
